(cl:in-package #:claraoke-subtitle)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Print script (ASS)
;;;
(defmethod claraoke:print-script ((object note) &optional stream)
  (princ #\; stream)
  (princ #\Space stream)
  (princ (claraoke:descriptor object) stream)
  (terpri stream)
  object)

(defmethod claraoke:print-script ((object info) &optional stream)
  (princ (claraoke:descriptor object) stream)
  (princ #\: stream)
  (princ #\Space stream)
  (princ (claraoke:value object) stream)
  (terpri stream)
  object)

(defmethod claraoke:print-script ((object subtitle) &optional stream)
  (claraoke:print-script (claraoke:lines object) stream)
  object)

(defmethod claraoke:print-script ((object cons) &optional stream)
  (loop for line in object
        do (claraoke:print-script line stream)
        finally (terpri stream))
  object)

(defmethod claraoke:print-script ((object vector) &optional stream)
  (loop for line across object
        do (claraoke:print-script line stream))
  object)

(defmethod claraoke:print-script ((object section) &optional stream)
  (let ((header (claraoke:header object))
        (lines (claraoke:lines object)))
    (unless (null lines)
      (princ #\[ stream)
      (princ (claraoke:descriptor object) stream)
      (princ #\] stream)
      (terpri stream)
      (unless (null header)
        (claraoke:print-script header stream)
        (terpri stream))
      (claraoke:print-script (reverse lines) stream)))
  object)

(defmethod claraoke:print-script ((object style) &optional stream)
  (let ((slots (list (claraoke:name object)
                     (claraoke:fontname object)
                     (claraoke:fontsize object)
                     (claraoke:primary-colour object)
                     (claraoke:secondary-colour object)
                     (claraoke:outline-colour object)
                     (claraoke:back-colour object)
                     (claraoke:bold object)
                     (claraoke:italic object)
                     (claraoke:underline object)
                     (claraoke:strike-out object)
                     (claraoke:scale-x object)
                     (claraoke:scale-y object)
                     (claraoke:spacing object)
                     (claraoke:angle object)
                     (claraoke:border-style object)
                     (claraoke:outline object)
                     (claraoke:.shadow object)
                     (claraoke:alignment object)
                     (claraoke:margin-l object)
                     (claraoke:margin-r object)
                     (claraoke:margin-v object)
                     (claraoke:encoding object)))
        (separator (claraoke:separator object)))
    (princ (claraoke:descriptor object) stream)
    (princ #\: stream)
    (princ #\Space stream)
    (princ (first slots) stream)
    (loop for slot in (rest slots)
          do (princ separator stream)
             (claraoke:print-script slot stream))
    (terpri stream))
  object)

(defmethod claraoke:print-script ((object event) &optional stream)
  (let ((slots (list (claraoke:layer object)
                     (claraoke:start object)
                     (claraoke:end object)
                     (claraoke:.style object)
                     (claraoke:name object)
                     (claraoke:margin-l object)
                     (claraoke:margin-r object)
                     (claraoke:margin-v object)
                     (claraoke:effect object)
                     (claraoke:.text object)))
        (separator (claraoke:separator object)))
    (princ (claraoke:descriptor object) stream)
    (princ #\: stream)
    (princ #\Space stream)
    (princ (first slots) stream)
    (loop for slot in (rest slots)
          do (princ separator stream)
             (claraoke:print-script slot stream))
    (terpri stream))
  object)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Print object
;;;
(defmethod print-object ((object note) stream)
  (print-unreadable-object (object stream :type nil :identity t)
    (princ "NOTE" stream)
    (princ #\Space stream)
    (prin1 (claraoke:descriptor object) stream)))

(defmethod print-object ((object info) stream)
  (print-unreadable-object (object stream :type nil :identity t)
    (princ (claraoke:descriptor object) stream)
    (princ #\Space stream)
    (prin1 (claraoke:value object) stream)))

(defmethod print-object ((object subtitle) stream)
  (print-unreadable-object (object stream :type nil :identity t)
    (let* ((info (claraoke:find-line (aref (claraoke:lines object) 0) "Title"))
           (title (if (null info)
                      "Untitled"
                      (claraoke:value info))))
      (princ "SUBTITLE" stream)
      (princ #\Space stream)
      (prin1 title stream))))

(defmethod print-object ((object style) stream)
  (print-unreadable-object (object stream :type nil :identity t)
    (princ "STYLE" stream)
    (princ #\Space stream)
    (prin1 (claraoke:name object) stream)))

(defmethod print-object ((object event) stream)
  (print-unreadable-object (object stream :type nil :identity nil)
    (let ((start (claraoke:start object))
          (end (claraoke:end object))
          (text (claraoke:.text object)))
      (print-object start stream)
      (princ " --> " stream)
      (print-object end stream)
      (princ #\Space stream)
      (if (stringp text)
          (prin1 text stream)
          (prin1 (claraoke:.text text) stream))
      (unless (stringp text)
        (princ #\Space stream)
        (princ #\( stream)
        (princ (length (claraoke:overrides text)) stream)
        (princ #\) stream)))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; Print remake
;;;
(defmethod claraoke:print-remake ((object subtitle) &optional stream (name "*sub*"))
  (let ((s-info (claraoke:script-info object))
        (styles (claraoke:styles object))
        (events (claraoke:events object)))
    (princ ";;; SUBTITLE" stream)
    (princ #\Newline stream)
    (princ #\( stream)
    (princ "defparameter" stream)
    (princ #\Space stream)
    (princ name stream)
    (princ #\Space stream)
    (princ #\( stream)
    (princ "subtitle" stream)
    (princ #\Space stream)
    (prin1 (claraoke:value
            (or (claraoke:find-info object "Title")
                (claraoke:info "Title" :value "Untitled")))
           stream)
    (princ #\Space stream)
    (princ ":text" stream)
    (princ #\Space stream)
    (princ "nil" stream)
    (princ #\Space stream)
    (princ ":style-name" stream)
    (princ #\Space stream)
    (princ "nil" stream)
    (claraoke:print-remake s-info stream name)
    (princ #\) stream)
    (princ #\) stream)
    (princ #\Newline stream)
    (princ #\Newline stream)
    (claraoke:print-remake styles stream name)
    (princ #\Newline stream)
    (claraoke:print-remake events stream name)
    (princ #\Newline stream)
    object))

(defun string-keyword (string)
  (with-output-to-string (stream)
    (princ #\: stream)
    (loop for i from 0
          for char across string
          when (and (plusp i) (upper-case-p char))
            do (princ #\- stream)
          do (princ (char-downcase char) stream))))

(defmethod claraoke:print-remake ((object script-info) &optional stream name)
  (declare (ignore name))
  (let ((default (claraoke:script-info "Untitled")))
    (loop for line in (claraoke:lines object)
          when (typep line 'info)
            do (let ((defa (claraoke:find-info default (claraoke:descriptor line))))
                 (unless (and defa (string= (princ-to-string (claraoke:value defa))
                                            (princ-to-string (claraoke:value line))))
                   (unless (string-equal "Title" (claraoke:descriptor line))
                     (princ #\Space stream)
                     (princ (string-keyword (claraoke:descriptor line)) stream)
                     (princ #\Space stream)
                     (prin1 (claraoke:value line) stream)))))
    object))

(defmethod claraoke:print-remake ((object styles) &optional stream (name "*sub*"))
  (let ((styles (claraoke:lines object)))
    (unless (null styles)
      (princ ";;; STYLES" stream)
      (princ #\Newline stream)
      (loop for style in (reverse styles)
            do (claraoke:print-remake style stream name)
               (princ #\Newline stream)))
    object))

(defmethod claraoke:print-remake ((object style) &optional stream (name "*sub*"))
  (let ((default (claraoke:style "compare")))
    (princ #\( stream)
    (princ "insert-style" stream)
    (princ #\Space stream)
    (princ name stream)
    (princ #\Space stream)
    (princ #\( stream)
    (princ "style" stream)
    (princ #\Space stream)
    (prin1 (claraoke:name object) stream)
    (unless (string-equal (claraoke:fontname object)
                          (claraoke:fontname default))
      (princ #\Space stream)
      (princ ":fontname" stream)
      (princ #\Space stream)
      (prin1 (claraoke:fontname object) stream))
    (unless (= (claraoke:fontsize object)
               (claraoke:fontsize default))
      (princ #\Space stream)
      (princ ":fontsize" stream)
      (princ #\Space stream)
      (princ (claraoke:fontsize object) stream))
    (unless (string-equal (claraoke:colorstring (claraoke:primary-colour object))
                          (claraoke:colorstring (claraoke:primary-colour default)))
      (princ #\Space stream)
      (princ ":primary-colour" stream)
      (princ #\Space stream)
      (prin1 (claraoke:colorstring (claraoke:primary-colour object)) stream))
    (unless (string-equal (claraoke:colorstring (claraoke:secondary-colour object))
                          (claraoke:colorstring (claraoke:secondary-colour default)))
      (princ #\Space stream)
      (princ ":secondary-colour" stream)
      (princ #\Space stream)
      (prin1 (claraoke:colorstring (claraoke:secondary-colour object)) stream))
    (unless (string-equal (claraoke:colorstring (claraoke:outline-colour object))
                          (claraoke:colorstring (claraoke:outline-colour default)))
      (princ #\Space stream)
      (princ ":outline-colour" stream)
      (princ #\Space stream)
      (prin1 (claraoke:colorstring (claraoke:outline-colour object)) stream))
    (unless (string-equal (claraoke:colorstring (claraoke:back-colour object))
                          (claraoke:colorstring (claraoke:back-colour default)))
      (princ #\Space stream)
      (princ ":back-colour" stream)
      (princ #\Space stream)
      (prin1 (claraoke:colorstring (claraoke:back-colour object)) stream))
    (unless (= (claraoke:bold object)
               (claraoke:bold default))
      (princ #\Space stream)
      (princ ":bold" stream)
      (princ #\Space stream)
      (princ (claraoke:bold object) stream))
    (unless (= (claraoke:italic object)
               (claraoke:italic default))
      (princ #\Space stream)
      (princ ":italic" stream)
      (princ #\Space stream)
      (princ (claraoke:italic object) stream))
    (unless (= (claraoke:underline object)
               (claraoke:underline default))
      (princ #\Space stream)
      (princ ":underline" stream)
      (princ #\Space stream)
      (princ (claraoke:underline object) stream))
    (unless (= (claraoke:strike-out object)
               (claraoke:strike-out default))
      (princ #\Space stream)
      (princ ":strike-out" stream)
      (princ #\Space stream)
      (princ (claraoke:strike-out object) stream))
    (unless (= (claraoke:scale-x object)
               (claraoke:scale-x default))
      (princ #\Space stream)
      (princ ":scale-x" stream)
      (princ #\Space stream)
      (princ (claraoke:scale-x object) stream))
    (unless (= (claraoke:scale-y object)
               (claraoke:scale-y default))
      (princ #\Space stream)
      (princ ":scale-y" stream)
      (princ #\Space stream)
      (princ (claraoke:scale-y object) stream))
    (unless (= (claraoke:spacing object)
               (claraoke:spacing default))
      (princ #\Space stream)
      (princ ":spacing" stream)
      (princ #\Space stream)
      (princ (claraoke:spacing object) stream))
    (unless (= (claraoke:angle object)
               (claraoke:angle default))
      (princ #\Space stream)
      (princ ":angle" stream)
      (princ #\Space stream)
      (princ (claraoke:angle object) stream))
    (unless (= (claraoke:border-style object)
               (claraoke:border-style default))
      (princ #\Space stream)
      (princ ":border-style" stream)
      (princ #\Space stream)
      (princ (claraoke:border-style object) stream))
    (unless (= (claraoke:outline object)
               (claraoke:outline default))
      (princ #\Space stream)
      (princ ":outline" stream)
      (princ #\Space stream)
      (princ (claraoke:outline object) stream))
    (unless (= (claraoke:.shadow object)
               (claraoke:.shadow default))
      (princ #\Space stream)
      (princ ":shadow" stream)
      (princ #\Space stream)
      (princ (claraoke:.shadow object) stream))
    (unless (= (claraoke:alignment object)
               (claraoke:alignment default))
      (princ #\Space stream)
      (princ ":alignment" stream)
      (princ #\Space stream)
      (princ (claraoke:alignment object) stream))
    (unless (= (claraoke:margin-l object)
               (claraoke:margin-l default))
      (princ #\Space stream)
      (princ ":margin-l" stream)
      (princ #\Space stream)
      (princ (claraoke:margin-l object) stream))
    (unless (= (claraoke:margin-r object)
               (claraoke:margin-r default))
      (princ #\Space stream)
      (princ ":margin-r" stream)
      (princ #\Space stream)
      (princ (claraoke:margin-r object) stream))
    (unless (= (claraoke:margin-v object)
               (claraoke:margin-v default))
      (princ #\Space stream)
      (princ ":margin-v" stream)
      (princ #\Space stream)
      (princ (claraoke:margin-v object) stream))
    (unless (= (claraoke:encoding object)
               (claraoke:encoding default))
      (princ #\Space stream)
      (princ ":encoding" stream)
      (princ #\Space stream)
      (princ (claraoke:encoding object) stream))
    (princ #\) stream)
    (princ #\) stream)
    object))

(defmethod claraoke:print-remake ((object events) &optional stream (name "*sub*"))
  (let ((events (claraoke:lines object))
        (ltime 0))
    (unless (null events)
      (princ ";;; DIALOGUES" stream)
      (princ #\Newline stream)
      (princ #\( stream)
      (princ "setf" stream)
      (princ #\Space stream)
      (princ #\( stream)
      (princ "interval" stream)
      (princ #\Space stream)
      (princ name stream)
      (princ #\) stream)
      (princ #\Space stream)
      (princ "0" stream)
      (princ #\) stream)
      (princ #\Newline stream)
      (princ #\Newline stream)
      (princ #\( stream)
      (princ "setf" stream)
      (princ #\Space stream)
      (princ #\( stream)
      (princ "interval-counter" stream)
      (princ #\Space stream)
      (princ name stream)
      (princ #\) stream)
      (princ #\Space stream)
      (princ #\( stream)
      (princ "durationinteger" stream)
      (princ #\Space stream)
      (prin1 (claraoke:durationstring 0) stream)
      (princ #\) stream)
      (princ #\) stream)
      (princ #\Newline stream)
      (loop for event in (reverse events)
            when (typep event 'dialogue)
              do (cond ((> 0 (- (claraoke:durationinteger
                                 (claraoke:start event))
                                (claraoke:durationinteger ltime)))
                        (setf ltime (claraoke:start event))
                        (princ #\Newline stream)
                        (princ #\( stream)
                        (princ "setf" stream)
                        (princ #\Space stream)
                        (princ #\( stream)
                        (princ "interval-counter" stream)
                        (princ #\Space stream)
                        (princ name stream)
                        (princ #\) stream)
                        (princ #\Space stream)
                        (princ #\( stream)
                        (princ "durationinteger" stream)
                        (princ #\Space stream)
                        (prin1 (claraoke:durationstring (claraoke:start event)) stream)
                        (princ #\) stream)
                        (princ #\) stream)
                        (princ #\Newline stream))
                       ((< 1 (- (claraoke:durationinteger
                                 (claraoke:start event))
                                (claraoke:durationinteger ltime)))
                        (princ #\Newline stream)
                        (princ #\( stream)
                        (princ "incf" stream)
                        (princ #\Space stream)
                        (princ #\( stream)
                        (princ "interval-counter" stream)
                        (princ #\Space stream)
                        (princ name stream)
                        (princ #\) stream)
                        (princ #\Space stream)
                        (princ #\( stream)
                        (princ "durationinteger" stream)
                        (princ #\Space stream)
                        (prin1 (claraoke:durationstring
                                (claraoke:duration-length (claraoke:start event) ltime))
                               stream)
                        (princ #\) stream)
                        (princ #\) stream)
                        (princ #\Newline stream)))
                 (claraoke:print-remake event stream name)
                 (princ #\Newline stream)
                 (setf ltime (claraoke:end event))))
    object))

(defmethod claraoke:print-remake ((object dialogue) &optional stream (name "*sub*"))
  (princ #\( stream)
  (princ "insert-event" stream)
  (princ #\Space stream)
  (princ name stream)
  (princ #\Space stream)
  (princ #\( stream)
  (princ "dialogue" stream)
  (princ #\Space stream)
  (prin1 (claraoke:.text (claraoke:.text object)) stream)
  (unless (string-equal "Default" (claraoke:style object))
    (princ #\Space stream)
    (princ ":style" stream)
    (princ #\Space stream)
    (prin1 (claraoke:style object) stream))
  (princ #\Space stream)
  (princ ":duration" stream)
  (princ #\Space stream)
  (prin1 (claraoke:durationstring (claraoke:duration-length object)) stream)
  (princ #\) stream)
  (princ #\) stream)
  object)

