(ql:quickload "claraoke-user" :silent t)

(in-package :claraoke-user)

(defparameter *mysub* (subtitle "Eyes on Me" :text nil :fontsize 72 :alignment 5 :italic -1))

(setf (interval *mysub*) 60)
(setf (interval-frequency *mysub*) 8)

;; Events
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line01* (dialogue "Whenever sang my songs" :generate-overrides-p t :spell-duration 30))
(defparameter *line02* (dialogue "On the stage, on my own" :generate-overrides-p t :spell-duration 30))
(defparameter *line03* (dialogue "Whenever said my words" :generate-overrides-p t :spell-duration 30))
(defparameter *line04* (dialogue "Wishing they would be heard" :generate-overrides-p t :spell-duration 30))
(defparameter *line05* (dialogue "I saw you smiling at me" :generate-overrides-p t :spell-duration 30))
(defparameter *line06* (dialogue "Was it real or just my fantasy" :generate-overrides-p t :spell-duration 30))
(defparameter *line07* (dialogue "You'd always be there in the corner" :generate-overrides-p t :spell-duration 30))
(defparameter *line08* (dialogue "Of this tiny little bar" :generate-overrides-p t :spell-duration 30))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line09* (dialogue "My last night here for you" :generate-overrides-p t :spell-duration 30))
(defparameter *line10* (dialogue "Same old songs, just once more" :generate-overrides-p t :spell-duration 30))
(defparameter *line11* (dialogue "My last night here with you?" :generate-overrides-p t :spell-duration 30))
(defparameter *line12* (dialogue "Maybe yes, maybe no" :generate-overrides-p t :spell-duration 30))
(defparameter *line13* (dialogue "I kind of liked it your way" :generate-overrides-p t :spell-duration 30))
(defparameter *line14* (dialogue "How you shyly placed your eyes on me" :generate-overrides-p t :spell-duration 30))
(defparameter *line15* (dialogue "Oh, did you ever know?" :generate-overrides-p t :spell-duration 30))
(defparameter *line16* (dialogue "That I had mine on you" :generate-overrides-p t :spell-duration 30))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line17* (dialogue "Darling, so there you are" :generate-overrides-p t :spell-duration 30))
(defparameter *line18* (dialogue "With that look on your face" :generate-overrides-p t :spell-duration 30))
(defparameter *line19* (dialogue "As if you're never hurt" :generate-overrides-p t :spell-duration 30))
(defparameter *line20* (dialogue "As if you're never down" :generate-overrides-p t :spell-duration 30))
(defparameter *line21* (dialogue "Shall I be the one for you" :generate-overrides-p t :spell-duration 30))
(defparameter *line22* (dialogue "Who pinches you softly but sure" :generate-overrides-p t :spell-duration 30))
(defparameter *line23* (dialogue "If frown is shown then" :generate-overrides-p t :spell-duration 30))
(defparameter *line24* (dialogue "I will know that you are no dreamer" :generate-overrides-p t :spell-duration 30))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line25* (dialogue "So let me come to you" :generate-overrides-p t :spell-duration 30))
(defparameter *line26* (dialogue "Close as I wanna be" :generate-overrides-p t :spell-duration 30))
(defparameter *line27* (dialogue "Close enough for me" :generate-overrides-p t :spell-duration 30))
(defparameter *line28* (dialogue "To feel your heart beating fast" :generate-overrides-p t :spell-duration 30))
(defparameter *line29* (dialogue "And stay there as I whisper" :generate-overrides-p t :spell-duration 30))
(defparameter *line30* (dialogue "How I loved your peaceful eyes on me" :generate-overrides-p t :spell-duration 30))
(defparameter *line31* (dialogue "Did you ever know" :generate-overrides-p t :spell-duration 30))
(defparameter *line32* (dialogue "That I had mine on you" :generate-overrides-p t :spell-duration 30))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line33* (dialogue "Darling, so share with me" :generate-overrides-p t :spell-duration 30))
(defparameter *line34* (dialogue "Your love if you have enough" :generate-overrides-p t :spell-duration 30))
(defparameter *line35* (dialogue "Your tears if you're holding back" :generate-overrides-p t :spell-duration 30))
(defparameter *line36* (dialogue "Or pain if that's what it is" :generate-overrides-p t :spell-duration 30))
(defparameter *line37* (dialogue "How can I let you know" :generate-overrides-p t :spell-duration 30))
(defparameter *line38* (dialogue "I'm more than the dress and the voice" :generate-overrides-p t :spell-duration 30))
(defparameter *line39* (dialogue "Just reach me out then" :generate-overrides-p t :spell-duration 30))
(defparameter *line40* (dialogue "You will know that you're not dreaming" :generate-overrides-p t :spell-duration 30))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *line41* (dialogue "Darling, so there you are" :generate-overrides-p t :spell-duration 30))
(defparameter *line42* (dialogue "With that look on your face" :generate-overrides-p t :spell-duration 30))
(defparameter *line43* (dialogue "As if you're never hurt" :generate-overrides-p t :spell-duration 30))
(defparameter *line44* (dialogue "As if you're never down" :generate-overrides-p t :spell-duration 30))
(defparameter *line45* (dialogue "Shall I be the one for you" :generate-overrides-p t :spell-duration 30))
(defparameter *line46* (dialogue "Who pinches you softly but sure" :generate-overrides-p t :spell-duration 30))
(defparameter *line47* (dialogue "If frown is shown then" :generate-overrides-p t :spell-duration 30))
(defparameter *line48* (dialogue "I will know that you are no dreamer" :generate-overrides-p t :spell-duration 30))

;; Overrides
;; TODO

;; Add lines with counter ( Autoincrement )
(setf (interval-counter *mysub*) (durationinteger "27.60"))
(insert-event *mysub* *line01* :interval-delay 0)
(insert-event *mysub* *line02*)
(insert-event *mysub* *line03*)
(insert-event *mysub* *line04*)
(insert-event *mysub* *line05*)
(insert-event *mysub* *line06* :interval-delay 0)
(insert-event *mysub* *line07*)
(insert-event *mysub* *line08* :interval-delay 0 :interval-event 10)
(setf (interval-counter *mysub*) (durationinteger "1:10.40"))
(insert-event *mysub* *line09* :interval-delay 0)
(insert-event *mysub* *line10*)
(insert-event *mysub* *line11*)
(insert-event *mysub* *line12*)
(insert-event *mysub* *line13*)
(insert-event *mysub* *line14* :interval-delay 0)
(insert-event *mysub* *line15*)
(insert-event *mysub* *line16* :interval-delay 0)
(setf (interval-counter *mysub*) (durationinteger "1:54.60"))
(insert-event *mysub* *line17* :interval-delay 0)
(insert-event *mysub* *line18*)
(insert-event *mysub* *line19*)
(insert-event *mysub* *line20*)
(insert-event *mysub* *line21* :interval-delay 0)
(insert-event *mysub* *line22* :interval-event 11)
(insert-event *mysub* *line23* :interval-delay 0 :interval-event 5)
(insert-event *mysub* *line24* :interval-delay 0 :interval-event 16)
(setf (interval-counter *mysub*) (durationinteger "3:4.80"))
(insert-event *mysub* *line25* :interval-delay 0)
(insert-event *mysub* *line26*)
(insert-event *mysub* *line27*)
(insert-event *mysub* *line28*)
(insert-event *mysub* *line29*)
(insert-event *mysub* *line30*)
(insert-event *mysub* *line31* :interval-event 7)
(insert-event *mysub* *line32* :interval-delay 0)
(setf (interval-counter *mysub*) (durationinteger "3:49.40"))
(insert-event *mysub* *line33* :interval-delay 0)
(insert-event *mysub* *line34*)
(insert-event *mysub* *line35*)
(insert-event *mysub* *line36* :interval-delay 0 :interval-event 9)
(insert-event *mysub* *line37*)
(insert-event *mysub* *line38* :interval-delay 0 :interval-event 10)
(insert-event *mysub* *line39* :interval-event 5)
(insert-event *mysub* *line40* :interval-delay 0 :interval-event 10)
(setf (interval-counter *mysub*) (durationinteger "4:32.40"))
(insert-event *mysub* *line41* :interval-delay 0)
(insert-event *mysub* *line42*)
(insert-event *mysub* *line43*)
(insert-event *mysub* *line44*)
(insert-event *mysub* *line45* :interval-delay 0)
(insert-event *mysub* *line46* :interval-event 11)
(insert-event *mysub* *line47* :interval-delay 0 :interval-event 5)
(insert-event *mysub* *line48* :interval-delay 0 :interval-event 16)

;; Disable counter
(setf (interval-counter *mysub*) nil)

;; Write to file
(claraoke-subtitle-to-file *mysub* #p"/tmp/mysub.ass")

