(cl:in-package #:claraoke-base)

(defclass claraoke:duration ()
  ((%hours
    :initform 0
    :initarg :h
    :initarg :hour
    :accessor claraoke:hours)
   (%minutes
    :initform 0
    :initarg :m
    :initarg :minute
    :accessor claraoke:minutes)
   (%seconds
    :initform 0
    :initarg :s
    :initarg :second
    :accessor claraoke:seconds)
   (%miliseconds
    :initform 0
    :initarg :ms
    :initarg :milisecond
    :accessor claraoke:miliseconds)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; These GFs already generated by class CLARAOKE:DURATION
;;;
;;; (defgeneric claraoke:hours (duration))
;;; (defgeneric claraoke:minutes (duration))
;;; (defgeneric claraoke:seconds (duration))
;;; (defgeneric claraoke:miliseconds (duration))
;;;

(defgeneric claraoke:duration (duration))

(defgeneric claraoke:durationp (duration))

(defgeneric claraoke:durationstring (duration))

(defgeneric claraoke:durationstringp (string))

(defgeneric claraoke:durationinteger (duration))

(defgeneric claraoke:durationintegerp (string))

(defgeneric claraoke:increase-duration (duration addition))

(defgeneric claraoke:decrease-duration (duration subtraction))

