(cl:in-package #:claraoke-base)

(defclass claraoke:duration ()
  ((%hours
    :initform 0
    :initarg :h
    :initarg :hours
    :accessor claraoke:hours)
   (%minutes
    :initform 0
    :initarg :m
    :initarg :minutes
    :accessor claraoke:minutes)
   (%seconds
    :initform 0
    :initarg :s
    :initarg :seconds
    :accessor claraoke:seconds)
   (%centiseconds
    :initform 0
    :initarg :cs
    :initarg :centiseconds
    :accessor claraoke:centiseconds)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;
;;; These GFs already generated by class CLARAOKE:DURATION
;;;
;;; (defgeneric claraoke:hours (duration))
;;; (defgeneric claraoke:minutes (duration))
;;; (defgeneric claraoke:seconds (duration))
;;; (defgeneric claraoke:centiseconds (duration))
;;;

(defgeneric claraoke:duration (duration))

(defgeneric claraoke:durationp (duration))

(defgeneric claraoke:durationstring (duration))

(defgeneric claraoke:durationstringp (string))

(defgeneric claraoke:durationinteger (duration))

(defgeneric claraoke:durationintegerp (string))

(defgeneric claraoke:increase-duration (duration addition))

(defgeneric claraoke:decrease-duration (duration subtraction))

