(cl:in-package #:cl-user)

(defpackage #:claraoke
  (:use)
  (:export
   #:.script-info
   #:.shadow
   #:.style
   #:.text
   #:alignment
   #:alpha
   #:angle
   #:arg1
   #:arg2
   #:arg3
   #:arg4
   #:arg5
   #:arg6
   #:arg7
   #:back-colour
   #:blue
   #:bold
   #:border-style
   #:centiseconds
   #:collisions
   #:color
   #:colorstring
   #:command
   #:comment
   #:decrease-duration
   #:decrease-karaoke
   #:decrease-override
   #:delete-event
   #:delete-font
   #:delete-graphic
   #:delete-info
   #:delete-line
   #:delete-note
   #:delete-override
   #:delete-style
   #:descriptor
   #:dialogue
   #:duration
   #:duration-difference
   #:duration-greaterp
   #:duration-length
   #:duration-lessp
   #:durationinteger
   #:durationintegerp
   #:durationp
   #:durationstring
   #:durationstringp
   #:effect
   #:encoding
   #:end
   #:event
   #:events
   #:failed-to-create-color
   #:failed-to-create-duration
   #:failed-to-create-events
   #:failed-to-create-fonts
   #:failed-to-create-graphics
   #:failed-to-create-info
   #:failed-to-create-integer
   #:failed-to-create-note
   #:failed-to-create-script-info
   #:failed-to-create-style
   #:failed-to-create-styles
   #:failed-to-create-subtitle
   #:failed-to-create-text
   #:find-event
   #:find-font
   #:find-graphic
   #:find-info
   #:find-line
   #:find-note
   #:find-override
   #:find-style
   #:font
   #:fontname
   #:fonts
   #:fontsize
   #:graphic
   #:graphics
   #:green
   #:header
   #:hours
   #:increase-duration
   #:increase-karaoke
   #:increase-override
   #:index
   #:info
   #:insert-event
   #:insert-font
   #:insert-graphic
   #:insert-info
   #:insert-line
   #:insert-note
   #:insert-override
   #:insert-style
   #:interval
   #:interval-counter
   #:interval-frequency
   #:italic
   #:last-event
   #:last-line
   #:last-style-storage
   #:layer
   #:line
   #:lines
   #:margin-l
   #:margin-r
   #:margin-v
   #:minutes
   #:movie
   #:name
   #:note
   #:null-object-warning
   #:object-must-be-color
   #:object-must-be-duration
   #:object-must-be-event
   #:object-must-be-events
   #:object-must-be-info
   #:object-must-be-integer
   #:object-must-be-line
   #:object-must-be-note
   #:object-must-be-override
   #:object-must-be-script
   #:object-must-be-script-info
   #:object-must-be-style
   #:object-must-be-styles
   #:object-must-be-subtitle
   #:object-must-be-text
   #:original-editing
   #:original-script
   #:original-text
   #:original-timing
   #:original-translation
   #:outline
   #:outline-colour
   #:override
   #:overrides
   #:parse-script
   #:picture
   #:play-depth
   #:play-res-x
   #:play-res-y
   #:primary-colour
   #:print-script
   #:random-color
   #:red
   #:rgb
   #:scale-x
   #:scale-y
   #:scaled-border-and-shadow
   #:script
   #:script-info
   #:script-type
   #:scrypt-update-by
   #:secondary-colour
   #:seconds
   #:section-line
   #:separator
   #:sort-events
   #:sort-overrides
   #:sound
   #:spacing
   #:start
   #:strike-out
   #:style
   #:styles
   #:subtitle
   #:sync-duration
   #:sync-point
   #:table-line
   #:text
   #:timer
   #:title
   #:underline
   #:update-details
   #:update-karaoke
   #:value
   #:value-mixin
   #:video-aspect-ratio
   #:video-position
   #:video-zoom
   #:wrap-style))

(defpackage #:claraoke-internal
  (:use #:common-lisp)
  (:export
   #:deletef
   #:digit-char-or-dot-p
   #:distinct-number-and-string
   #:integer-from-string
   #:mimic-accessor
   #:number-or-string
   #:output-stream-from-designator
   #:print-symbols
   #:script-note
   #:version))

(defpackage #:claraoke-base
  (:use #:common-lisp))

