(cl:in-package #:cl-user)

(defpackage #:claraoke
  (:use)
  (:export
   #:.shadow
   #:.style
   #:.text
   #:alignment
   #:alpha
   #:alphap
   #:alphastring
   #:alphastringp
   #:angle
   #:arg1
   #:arg2
   #:arg3
   #:arg4
   #:arg5
   #:arg6
   #:arg7
   #:back-colour
   #:blue
   #:bold
   #:border-style
   #:centiseconds
   #:color
   #:colorp
   #:colorstring
   #:colorstringp
   #:command
   #:comment
   #:decrease-duration
   #:decrease-karaoke
   #:decrease-modifier
   #:decrease-override
   #:delete-event
   #:delete-font
   #:delete-graphic
   #:delete-info
   #:delete-line
   #:delete-modifier
   #:delete-note
   #:delete-override
   #:delete-style
   #:descriptor
   #:dialogue
   #:duration
   #:duration-difference
   #:duration-greaterp
   #:duration-length
   #:duration-lessp
   #:durationinteger
   #:durationintegerp
   #:durationp
   #:durationstring
   #:durationstringp
   #:effect
   #:encoding
   #:end
   #:events
   #:failed-to-create-color
   #:failed-to-create-duration
   #:failed-to-create-events
   #:failed-to-create-fonts
   #:failed-to-create-graphics
   #:failed-to-create-info
   #:failed-to-create-integer
   #:failed-to-create-note
   #:failed-to-create-script-info
   #:failed-to-create-style
   #:failed-to-create-styles
   #:failed-to-create-subtitle
   #:failed-to-create-text
   #:find-event
   #:find-font
   #:find-graphic
   #:find-info
   #:find-line
   #:find-modifier
   #:find-note
   #:find-override
   #:find-style
   #:font
   #:fontname
   #:fonts
   #:fontsize
   #:graphic
   #:graphics
   #:green
   #:header
   #:hours
   #:increase-duration
   #:increase-karaoke
   #:increase-modifier
   #:increase-override
   #:index
   #:info
   #:insert-event
   #:insert-font
   #:insert-graphic
   #:insert-info
   #:insert-karaoke
   #:insert-karaoke-fill
   #:insert-karaoke-outline
   #:insert-line
   #:insert-modifier
   #:insert-note
   #:insert-override
   #:insert-style
   #:interval
   #:interval-counter
   #:interval-frequency
   #:italic
   #:last-event
   #:last-line
   #:layer
   #:line
   #:lines
   #:margin-l
   #:margin-r
   #:margin-v
   #:minutes
   #:modifier
   #:modifiers
   #:movie
   #:name
   #:note
   #:null-object-warning
   #:object-must-be-batch
   #:object-must-be-color
   #:object-must-be-duration
   #:object-must-be-event
   #:object-must-be-events
   #:object-must-be-info
   #:object-must-be-integer
   #:object-must-be-line
   #:object-must-be-modifier
   #:object-must-be-note
   #:object-must-be-override
   #:object-must-be-script
   #:object-must-be-script-info
   #:object-must-be-style
   #:object-must-be-styles
   #:object-must-be-subtitle
   #:object-must-be-text
   #:original-text
   #:outline
   #:outline-colour
   #:override
   #:overrides
   #:parse-script
   #:picture
   #:primary-colour
   #:print-script
   #:random-color
   #:red
   #:rgb
   #:scale-x
   #:scale-y
   #:script
   #:script-info
   #:secondary-colour
   #:seconds
   #:section-line
   #:separator
   #:sort-events
   #:sort-overrides
   #:sound
   #:spacing
   #:start
   #:strike-out
   #:style
   #:styles
   #:subtitle
   #:synch-duration
   #:table-line
   #:text
   #:underline
   #:update-karaoke
   #:update-modifier
   #:value
   #:value-mixin))

(defpackage #:claraoke-internal
  (:use #:common-lisp)
  (:export
   #:deletef
   #:distinct-number-and-string
   #:integer-from-string
   #:mimic-accessor
   #:number-or-string
   #:number-string-p
   #:output-stream-from-designator
   #:print-symbols
   #:script-note
   #:sortf
   #:split-by-char
   #:split-by-char-to-keys
   #:version))

(defpackage #:claraoke-base
  (:use #:common-lisp))

