(cl:in-package #:claraoke-color)

(register-color-name "black" "#000000")
(register-color-name "dim gray" "#696969")
(register-color-name "dark gray" "#a9a9a9")
(register-color-name "gray" "#bebebe")
(register-color-name "light gray" "#d3d3d3")
(register-color-name "gainsboro" "#dcdcdc")
(register-color-name "white smoke" "#f5f5f5")
(register-color-name "white" "#ffffff")
(register-color-name "red" "#ff0000")
(register-color-name "orange red" "#ff4500")
(register-color-name "dark orange" "#ff8c00")
(register-color-name "orange" "#ffa500")
(register-color-name "gold" "#ffd700")
(register-color-name "yellow" "#ffff00")
(register-color-name "chartreuse" "#7fff00")
(register-color-name "lawn green" "#7cfc00")
(register-color-name "green" "#00ff00")
(register-color-name "spring green" "#00ff7f")
(register-color-name "medium spring green" "#00fa9a")
(register-color-name "cyan" "#00ffff")
(register-color-name "deep sky blue" "#00bfff")
(register-color-name "blue" "#0000ff")
(register-color-name "medium blue" "#0000cd")
(register-color-name "dark violet" "#9400d3")
(register-color-name "dark magenta" "#8b008b")
(register-color-name "magenta" "#ff00ff")
(register-color-name "dark red" "#8b0000")
(register-color-name "brown" "#a52a2a")
(register-color-name "firebrick" "#b22222")
(register-color-name "indian red" "#cd5c5c")
(register-color-name "light coral" "#f08080")
(register-color-name "salmon" "#fa8072")
(register-color-name "light salmon" "#ffa07a")
(register-color-name "tomato" "#ff6347")
(register-color-name "coral" "#ff7f50")
(register-color-name "dark salmon" "#e9967a")
(register-color-name "rosy brown" "#bc8f8f")
(register-color-name "sienna" "#a0522d")
(register-color-name "saddle brown" "#8b4513")
(register-color-name "chocolate" "#d2691e")
(register-color-name "peru" "#cd853f")
(register-color-name "sandy brown" "#f4a460")
(register-color-name "burlywood" "#deb887")
(register-color-name "tan" "#d2b48c")
(register-color-name "navajo white" "#ffdead")
(register-color-name "wheat" "#f5deb3")
(register-color-name "dark goldenrod" "#b8860b")
(register-color-name "goldenrod" "#daa520")
(register-color-name "light goldenrod" "#eedd82")
(register-color-name "pale goldenrod" "#eee8aa")
(register-color-name "cornsilk" "#fff8dc")
(register-color-name "dark khaki" "#bdb76b")
(register-color-name "khaki" "#f0e68c")
(register-color-name "lemon chiffon" "#fffacd")
(register-color-name "dark olive green" "#556b2f")
(register-color-name "olive drab" "#6b8e23")
(register-color-name "yellow green" "#9acd32")
(register-color-name "green yellow" "#adff2f")
(register-color-name "light green" "#90ee90")
(register-color-name "forest green" "#228b22")
(register-color-name "dark green" "#006400")
(register-color-name "lime green" "#32cd32")
(register-color-name "pale green" "#98fb98")
(register-color-name "dark sea green" "#8fbc8f")
(register-color-name "sea green" "#2e8b57")
(register-color-name "medium sea green" "#3cb371")
(register-color-name "light sea green" "#20b2aa")
(register-color-name "medium aquamarine" "#66cdaa")
(register-color-name "aquamarine" "#7fffd4")
(register-color-name "dark cyan" "#008b8b")
(register-color-name "dark turquoise" "#00ced1")
(register-color-name "medium turquoise" "#48d1cc")
(register-color-name "turquoise" "#40e0d0")
(register-color-name "pale turquoise" "#afeeee")
(register-color-name "powder blue" "#b0e0e6")
(register-color-name "light blue" "#add8e6")
(register-color-name "sky blue" "#87ceeb")
(register-color-name "light sky blue" "#87cefa")
(register-color-name "cadet blue" "#5f9ea0")
(register-color-name "steel blue" "#4682b4")
(register-color-name "dark slate gray" "#2f4f4f")
(register-color-name "slate gray" "#708090")
(register-color-name "light slate gray" "#778899")
(register-color-name "royal blue" "#4169e1")
(register-color-name "dodger blue" "#1e90ff")
(register-color-name "cornflower blue" "#6495ed")
(register-color-name "light steel blue" "#b0c4de")
(register-color-name "dark blue" "#00008b")
(register-color-name "navy" "#000080")
(register-color-name "midnight blue" "#191970")
(register-color-name "dark slate blue" "#483d8b")
(register-color-name "slate blue" "#6a5acd")
(register-color-name "medium slate blue" "#7b68ee")
(register-color-name "light slate blue" "#8470ff")
(register-color-name "medium purple" "#9370db")
(register-color-name "blue violet" "#8a2be2")
(register-color-name "purple" "#a020f0")
(register-color-name "dark orchid" "#9932cc")
(register-color-name "medium orchid" "#ba55d3")
(register-color-name "orchid" "#da70d6")
(register-color-name "thistle" "#d8bfd8")
(register-color-name "plum" "#dda0dd")
(register-color-name "violet" "#ee82ee")
(register-color-name "medium violet red" "#c71585")
(register-color-name "violet red" "#d02090")
(register-color-name "pale violet red" "#db7093")
(register-color-name "maroon" "#b03060")
(register-color-name "deep pink" "#ff1493")
(register-color-name "hot pink" "#ff69b4")
(register-color-name "pink" "#ffc0cb")
(register-color-name "light pink" "#ffb6c1")
(register-color-name "snow" "#fffafa")
(register-color-name "misty rose" "#ffe4e1")
(register-color-name "seashell" "#fff5ee")
(register-color-name "peach puff" "#ffdab9")
(register-color-name "linen" "#faf0e6")
(register-color-name "antique white" "#faebd7")
(register-color-name "bisque" "#ffe4c4")
(register-color-name "papaya whip" "#ffefd5")
(register-color-name "moccasin" "#ffe4b5")
(register-color-name "blanched almond" "#ffebcd")
(register-color-name "old lace" "#fdf5e6")
(register-color-name "floral white" "#fffaf0")
(register-color-name "beige" "#f5f5dc")
(register-color-name "light yellow" "#ffffe0")
(register-color-name "light goldenrod yellow" "#fafad2")
(register-color-name "ivory" "#fffff0")
(register-color-name "honeydew" "#f0fff0")
(register-color-name "mint cream" "#f5fffa")
(register-color-name "light cyan" "#e0ffff")
(register-color-name "azure" "#f0ffff")
(register-color-name "alice blue" "#f0f8ff")
(register-color-name "lavender" "#e6e6fa")
(register-color-name "ghost white" "#f8f8ff")
(register-color-name "lavender blush" "#fff0f5")
(register-color-name "red4" "#8b0000")
(register-color-name "red3" "#cd0000")
(register-color-name "red2" "#ee0000")
(register-color-name "red1" "#ff0000")
(register-color-name "OrangeRed4" "#8b2500")
(register-color-name "OrangeRed3" "#cd3700")
(register-color-name "OrangeRed2" "#ee4000")
(register-color-name "OrangeRed1" "#ff4500")
(register-color-name "DarkOrange4" "#8b4500")
(register-color-name "DarkOrange3" "#cd6600")
(register-color-name "DarkOrange2" "#ee7600")
(register-color-name "DarkOrange1" "#ff7f00")
(register-color-name "orange4" "#8b5a00")
(register-color-name "orange3" "#cd8500")
(register-color-name "orange2" "#ee9a00")
(register-color-name "orange1" "#ffa500")
(register-color-name "gold4" "#8b7500")
(register-color-name "gold3" "#cdad00")
(register-color-name "gold2" "#eec900")
(register-color-name "gold1" "#ffd700")
(register-color-name "yellow4" "#8b8b00")
(register-color-name "yellow3" "#cdcd00")
(register-color-name "yellow2" "#eeee00")
(register-color-name "yellow1" "#ffff00")
(register-color-name "chartreuse4" "#458b00")
(register-color-name "chartreuse3" "#66cd00")
(register-color-name "chartreuse2" "#76ee00")
(register-color-name "chartreuse1" "#7fff00")
(register-color-name "green4" "#008b00")
(register-color-name "green3" "#00cd00")
(register-color-name "green2" "#00ee00")
(register-color-name "green1" "#00ff00")
(register-color-name "SpringGreen4" "#008b45")
(register-color-name "SpringGreen3" "#00cd66")
(register-color-name "SpringGreen2" "#00ee76")
(register-color-name "SpringGreen1" "#00ff7f")
(register-color-name "cyan4" "#008b8b")
(register-color-name "cyan3" "#00cdcd")
(register-color-name "cyan2" "#00eeee")
(register-color-name "cyan1" "#00ffff")
(register-color-name "turquoise4" "#00868b")
(register-color-name "turquoise3" "#00c5cd")
(register-color-name "turquoise2" "#00e5ee")
(register-color-name "turquoise1" "#00f5ff")
(register-color-name "DeepSkyBlue4" "#00688b")
(register-color-name "DeepSkyBlue3" "#009acd")
(register-color-name "DeepSkyBlue2" "#00b2ee")
(register-color-name "DeepSkyBlue1" "#00bfff")
(register-color-name "blue4" "#00008b")
(register-color-name "blue3" "#0000cd")
(register-color-name "blue2" "#0000ee")
(register-color-name "blue1" "#0000ff")
(register-color-name "magenta4" "#8b008b")
(register-color-name "magenta3" "#cd00cd")
(register-color-name "magenta2" "#ee00ee")
(register-color-name "magenta1" "#ff00ff")
(register-color-name "brown4" "#8b2323")
(register-color-name "brown3" "#cd3333")
(register-color-name "brown2" "#ee3b3b")
(register-color-name "brown1" "#ff4040")
(register-color-name "firebrick4" "#8b1a1a")
(register-color-name "firebrick3" "#cd2626")
(register-color-name "firebrick2" "#ee2c2c")
(register-color-name "firebrick1" "#ff3030")
(register-color-name "IndianRed4" "#8b3a3a")
(register-color-name "IndianRed3" "#cd5555")
(register-color-name "IndianRed2" "#ee6363")
(register-color-name "IndianRed1" "#ff6a6a")
(register-color-name "RosyBrown4" "#8b6969")
(register-color-name "RosyBrown3" "#cd9b9b")
(register-color-name "RosyBrown2" "#eeb4b4")
(register-color-name "RosyBrown1" "#ffc1c1")
(register-color-name "snow4" "#8b8989")
(register-color-name "snow3" "#cdc9c9")
(register-color-name "snow2" "#eee9e9")
(register-color-name "snow1" "#fffafa")
(register-color-name "MistyRose4" "#8b7d7b")
(register-color-name "MistyRose3" "#cdb7b5")
(register-color-name "MistyRose2" "#eed5d2")
(register-color-name "MistyRose1" "#ffe4e1")
(register-color-name "tomato4" "#8b3626")
(register-color-name "tomato3" "#cd4f39")
(register-color-name "tomato2" "#ee5c42")
(register-color-name "tomato1" "#ff6347")
(register-color-name "coral4" "#8b3e2f")
(register-color-name "coral3" "#cd5b45")
(register-color-name "coral2" "#ee6a50")
(register-color-name "coral1" "#ff7256")
(register-color-name "salmon4" "#8b4c39")
(register-color-name "salmon3" "#cd7054")
(register-color-name "salmon2" "#ee8262")
(register-color-name "salmon1" "#ff8c69")
(register-color-name "LightSalmon4" "#8b5742")
(register-color-name "LightSalmon3" "#cd8162")
(register-color-name "LightSalmon2" "#ee9572")
(register-color-name "LightSalmon1" "#ffa07a")
(register-color-name "sienna4" "#8b4726")
(register-color-name "sienna3" "#cd6839")
(register-color-name "sienna2" "#ee7942")
(register-color-name "sienna1" "#ff8247")
(register-color-name "chocolate4" "#8b4513")
(register-color-name "chocolate3" "#cd661d")
(register-color-name "chocolate2" "#ee7621")
(register-color-name "chocolate1" "#ff7f24")
(register-color-name "seashell4" "#8b8682")
(register-color-name "seashell3" "#cdc5bf")
(register-color-name "seashell2" "#eee5de")
(register-color-name "seashell1" "#fff5ee")
(register-color-name "PeachPuff4" "#8b7765")
(register-color-name "PeachPuff3" "#cdaf95")
(register-color-name "PeachPuff2" "#eecbad")
(register-color-name "PeachPuff1" "#ffdab9")
(register-color-name "tan4" "#8b5a2b")
(register-color-name "tan3" "#cd853f")
(register-color-name "tan2" "#ee9a49")
(register-color-name "tan1" "#ffa54f")
(register-color-name "bisque4" "#8b7d6b")
(register-color-name "bisque3" "#cdb79e")
(register-color-name "bisque2" "#eed5b7")
(register-color-name "bisque1" "#ffe4c4")
(register-color-name "AntiqueWhite4" "#8b8378")
(register-color-name "AntiqueWhite3" "#cdc0b0")
(register-color-name "AntiqueWhite2" "#eedfcc")
(register-color-name "AntiqueWhite1" "#ffefdb")
(register-color-name "burlywood4" "#8b7355")
(register-color-name "burlywood3" "#cdaa7d")
(register-color-name "burlywood2" "#eec591")
(register-color-name "burlywood1" "#ffd39b")
(register-color-name "NavajoWhite4" "#8b795e")
(register-color-name "NavajoWhite3" "#cdb38b")
(register-color-name "NavajoWhite2" "#eecfa1")
(register-color-name "NavajoWhite1" "#ffdead")
(register-color-name "wheat4" "#8b7e66")
(register-color-name "wheat3" "#cdba96")
(register-color-name "wheat2" "#eed8ae")
(register-color-name "wheat1" "#ffe7ba")
(register-color-name "DarkGoldenrod4" "#8b6508")
(register-color-name "DarkGoldenrod3" "#cd950c")
(register-color-name "DarkGoldenrod2" "#eead0e")
(register-color-name "DarkGoldenrod1" "#ffb90f")
(register-color-name "goldenrod4" "#8b6914")
(register-color-name "goldenrod3" "#cd9b1d")
(register-color-name "goldenrod2" "#eeb422")
(register-color-name "goldenrod1" "#ffc125")
(register-color-name "cornsilk4" "#8b8878")
(register-color-name "cornsilk3" "#cdc8b1")
(register-color-name "cornsilk2" "#eee8cd")
(register-color-name "cornsilk1" "#fff8dc")
(register-color-name "LightGoldenrod4" "#8b814c")
(register-color-name "LightGoldenrod3" "#cdbe70")
(register-color-name "LightGoldenrod2" "#eedc82")
(register-color-name "LightGoldenrod1" "#ffec8b")
(register-color-name "LemonChiffon4" "#8b8970")
(register-color-name "LemonChiffon3" "#cdc9a5")
(register-color-name "LemonChiffon2" "#eee9bf")
(register-color-name "LemonChiffon1" "#fffacd")
(register-color-name "khaki4" "#8b864e")
(register-color-name "khaki3" "#cdc673")
(register-color-name "khaki2" "#eee685")
(register-color-name "khaki1" "#fff68f")
(register-color-name "LightYellow4" "#8b8b7a")
(register-color-name "LightYellow3" "#cdcdb4")
(register-color-name "LightYellow2" "#eeeed1")
(register-color-name "LightYellow1" "#ffffe0")
(register-color-name "ivory4" "#8b8b83")
(register-color-name "ivory3" "#cdcdc1")
(register-color-name "ivory2" "#eeeee0")
(register-color-name "ivory1" "#fffff0")
(register-color-name "OliveDrab4" "#698b22")
(register-color-name "OliveDrab3" "#9acd32")
(register-color-name "OliveDrab2" "#b3ee3a")
(register-color-name "OliveDrab1" "#c0ff3e")
(register-color-name "DarkOliveGreen4" "#6e8b3d")
(register-color-name "DarkOliveGreen3" "#a2cd5a")
(register-color-name "DarkOliveGreen2" "#bcee68")
(register-color-name "DarkOliveGreen1" "#caff70")
(register-color-name "PaleGreen4" "#548b54")
(register-color-name "PaleGreen3" "#7ccd7c")
(register-color-name "PaleGreen2" "#90ee90")
(register-color-name "PaleGreen1" "#9aff9a")
(register-color-name "DarkSeaGreen4" "#698b69")
(register-color-name "DarkSeaGreen3" "#9bcd9b")
(register-color-name "DarkSeaGreen2" "#b4eeb4")
(register-color-name "DarkSeaGreen1" "#c1ffc1")
(register-color-name "honeydew4" "#838b83")
(register-color-name "honeydew3" "#c1cdc1")
(register-color-name "honeydew2" "#e0eee0")
(register-color-name "honeydew1" "#f0fff0")
(register-color-name "SeaGreen4" "#2e8b57")
(register-color-name "SeaGreen3" "#43cd80")
(register-color-name "SeaGreen2" "#4eee94")
(register-color-name "SeaGreen1" "#54ff9f")
(register-color-name "aquamarine4" "#458b74")
(register-color-name "aquamarine3" "#66cdaa")
(register-color-name "aquamarine2" "#76eec6")
(register-color-name "aquamarine1" "#7fffd4")
(register-color-name "DarkSlateGray4" "#528b8b")
(register-color-name "DarkSlateGray3" "#79cdcd")
(register-color-name "DarkSlateGray2" "#8deeee")
(register-color-name "DarkSlateGray1" "#97ffff")
(register-color-name "PaleTurquoise4" "#668b8b")
(register-color-name "PaleTurquoise3" "#96cdcd")
(register-color-name "PaleTurquoise2" "#aeeeee")
(register-color-name "PaleTurquoise1" "#bbffff")
(register-color-name "LightCyan4" "#7a8b8b")
(register-color-name "LightCyan3" "#b4cdcd")
(register-color-name "LightCyan2" "#d1eeee")
(register-color-name "LightCyan1" "#e0ffff")
(register-color-name "azure4" "#838b8b")
(register-color-name "azure3" "#c1cdcd")
(register-color-name "azure2" "#e0eeee")
(register-color-name "azure1" "#f0ffff")
(register-color-name "CadetBlue4" "#53868b")
(register-color-name "CadetBlue3" "#7ac5cd")
(register-color-name "CadetBlue2" "#8ee5ee")
(register-color-name "CadetBlue1" "#98f5ff")
(register-color-name "LightBlue4" "#68838b")
(register-color-name "LightBlue3" "#9ac0cd")
(register-color-name "LightBlue2" "#b2dfee")
(register-color-name "LightBlue1" "#bfefff")
(register-color-name "LightSkyBlue4" "#607b8b")
(register-color-name "LightSkyBlue3" "#8db6cd")
(register-color-name "LightSkyBlue2" "#a4d3ee")
(register-color-name "LightSkyBlue1" "#b0e2ff")
(register-color-name "SkyBlue4" "#4a708b")
(register-color-name "SkyBlue3" "#6ca6cd")
(register-color-name "SkyBlue2" "#7ec0ee")
(register-color-name "SkyBlue1" "#87ceff")
(register-color-name "SteelBlue4" "#36648b")
(register-color-name "SteelBlue3" "#4f94cd")
(register-color-name "SteelBlue2" "#5cacee")
(register-color-name "SteelBlue1" "#63b8ff")
(register-color-name "DodgerBlue4" "#104e8b")
(register-color-name "DodgerBlue3" "#1874cd")
(register-color-name "DodgerBlue2" "#1c86ee")
(register-color-name "DodgerBlue1" "#1e90ff")
(register-color-name "SlateGray4" "#6c7b8b")
(register-color-name "SlateGray3" "#9fb6cd")
(register-color-name "SlateGray2" "#b9d3ee")
(register-color-name "SlateGray1" "#c6e2ff")
(register-color-name "LightSteelBlue4" "#6e7b8b")
(register-color-name "LightSteelBlue3" "#a2b5cd")
(register-color-name "LightSteelBlue2" "#bcd2ee")
(register-color-name "LightSteelBlue1" "#cae1ff")
(register-color-name "RoyalBlue4" "#27408b")
(register-color-name "RoyalBlue3" "#3a5fcd")
(register-color-name "RoyalBlue2" "#436eee")
(register-color-name "RoyalBlue1" "#4876ff")
(register-color-name "SlateBlue4" "#473c8b")
(register-color-name "SlateBlue3" "#6959cd")
(register-color-name "SlateBlue2" "#7a67ee")
(register-color-name "SlateBlue1" "#836fff")
(register-color-name "MediumPurple4" "#5d478b")
(register-color-name "MediumPurple3" "#8968cd")
(register-color-name "MediumPurple2" "#9f79ee")
(register-color-name "MediumPurple1" "#ab82ff")
(register-color-name "purple4" "#551a8b")
(register-color-name "purple3" "#7d26cd")
(register-color-name "purple2" "#912cee")
(register-color-name "purple1" "#9b30ff")
(register-color-name "DarkOrchid4" "#68228b")
(register-color-name "DarkOrchid3" "#9a32cd")
(register-color-name "DarkOrchid2" "#b23aee")
(register-color-name "DarkOrchid1" "#bf3eff")
(register-color-name "MediumOrchid4" "#7a378b")
(register-color-name "MediumOrchid3" "#b452cd")
(register-color-name "MediumOrchid2" "#d15fee")
(register-color-name "MediumOrchid1" "#e066ff")
(register-color-name "thistle4" "#8b7b8b")
(register-color-name "thistle3" "#cdb5cd")
(register-color-name "thistle2" "#eed2ee")
(register-color-name "thistle1" "#ffe1ff")
(register-color-name "plum4" "#8b668b")
(register-color-name "plum3" "#cd96cd")
(register-color-name "plum2" "#eeaeee")
(register-color-name "plum1" "#ffbbff")
(register-color-name "orchid4" "#8b4789")
(register-color-name "orchid3" "#cd69c9")
(register-color-name "orchid2" "#ee7ae9")
(register-color-name "orchid1" "#ff83fa")
(register-color-name "maroon4" "#8b1c62")
(register-color-name "maroon3" "#cd2990")
(register-color-name "maroon2" "#ee30a7")
(register-color-name "maroon1" "#ff34b3")
(register-color-name "DeepPink4" "#8b0a50")
(register-color-name "DeepPink3" "#cd1076")
(register-color-name "DeepPink2" "#ee1289")
(register-color-name "DeepPink1" "#ff1493")
(register-color-name "HotPink4" "#8b3a62")
(register-color-name "HotPink3" "#cd6090")
(register-color-name "HotPink2" "#ee6aa7")
(register-color-name "HotPink1" "#ff6eb4")
(register-color-name "VioletRed4" "#8b2252")
(register-color-name "VioletRed3" "#cd3278")
(register-color-name "VioletRed2" "#ee3a8c")
(register-color-name "VioletRed1" "#ff3e96")
(register-color-name "LavenderBlush4" "#8b8386")
(register-color-name "LavenderBlush3" "#cdc1c5")
(register-color-name "LavenderBlush2" "#eee0e5")
(register-color-name "LavenderBlush1" "#fff0f5")
(register-color-name "PaleVioletRed4" "#8b475d")
(register-color-name "PaleVioletRed3" "#cd6889")
(register-color-name "PaleVioletRed2" "#ee799f")
(register-color-name "PaleVioletRed1" "#ff82ab")
(register-color-name "pink4" "#8b636c")
(register-color-name "pink3" "#cd919e")
(register-color-name "pink2" "#eea9b8")
(register-color-name "pink1" "#ffb5c5")
(register-color-name "LightPink4" "#8b5f65")
(register-color-name "LightPink3" "#cd8c95")
(register-color-name "LightPink2" "#eea2ad")
(register-color-name "LightPink1" "#ffaeb9")
(register-color-name "gray0" "#000000")
(register-color-name "gray1" "#030303")
(register-color-name "gray2" "#050505")
(register-color-name "gray3" "#080808")
(register-color-name "gray4" "#0a0a0a")
(register-color-name "gray5" "#0d0d0d")
(register-color-name "gray6" "#0f0f0f")
(register-color-name "gray7" "#121212")
(register-color-name "gray8" "#141414")
(register-color-name "gray9" "#171717")
(register-color-name "gray10" "#1a1a1a")
(register-color-name "gray11" "#1c1c1c")
(register-color-name "gray12" "#1f1f1f")
(register-color-name "gray13" "#212121")
(register-color-name "gray14" "#242424")
(register-color-name "gray15" "#262626")
(register-color-name "gray16" "#292929")
(register-color-name "gray17" "#2b2b2b")
(register-color-name "gray18" "#2e2e2e")
(register-color-name "gray19" "#303030")
(register-color-name "gray20" "#333333")
(register-color-name "gray21" "#363636")
(register-color-name "gray22" "#383838")
(register-color-name "gray23" "#3b3b3b")
(register-color-name "gray24" "#3d3d3d")
(register-color-name "gray25" "#404040")
(register-color-name "gray26" "#424242")
(register-color-name "gray27" "#454545")
(register-color-name "gray28" "#474747")
(register-color-name "gray29" "#4a4a4a")
(register-color-name "gray30" "#4d4d4d")
(register-color-name "gray31" "#4f4f4f")
(register-color-name "gray32" "#525252")
(register-color-name "gray33" "#545454")
(register-color-name "gray34" "#575757")
(register-color-name "gray35" "#595959")
(register-color-name "gray36" "#5c5c5c")
(register-color-name "gray37" "#5e5e5e")
(register-color-name "gray38" "#616161")
(register-color-name "gray39" "#636363")
(register-color-name "gray40" "#666666")
(register-color-name "gray41" "#696969")
(register-color-name "gray42" "#6b6b6b")
(register-color-name "gray43" "#6e6e6e")
(register-color-name "gray44" "#707070")
(register-color-name "gray45" "#737373")
(register-color-name "gray46" "#757575")
(register-color-name "gray47" "#787878")
(register-color-name "gray48" "#7a7a7a")
(register-color-name "gray49" "#7d7d7d")
(register-color-name "gray50" "#7f7f7f")
(register-color-name "gray51" "#828282")
(register-color-name "gray52" "#858585")
(register-color-name "gray53" "#878787")
(register-color-name "gray54" "#8a8a8a")
(register-color-name "gray55" "#8c8c8c")
(register-color-name "gray56" "#8f8f8f")
(register-color-name "gray57" "#919191")
(register-color-name "gray58" "#949494")
(register-color-name "gray59" "#969696")
(register-color-name "gray60" "#999999")
(register-color-name "gray61" "#9c9c9c")
(register-color-name "gray62" "#9e9e9e")
(register-color-name "gray63" "#a1a1a1")
(register-color-name "gray64" "#a3a3a3")
(register-color-name "gray65" "#a6a6a6")
(register-color-name "gray66" "#a8a8a8")
(register-color-name "gray67" "#ababab")
(register-color-name "gray68" "#adadad")
(register-color-name "gray69" "#b0b0b0")
(register-color-name "gray70" "#b3b3b3")
(register-color-name "gray71" "#b5b5b5")
(register-color-name "gray72" "#b8b8b8")
(register-color-name "gray73" "#bababa")
(register-color-name "gray74" "#bdbdbd")
(register-color-name "gray75" "#bfbfbf")
(register-color-name "gray76" "#c2c2c2")
(register-color-name "gray77" "#c4c4c4")
(register-color-name "gray78" "#c7c7c7")
(register-color-name "gray79" "#c9c9c9")
(register-color-name "gray80" "#cccccc")
(register-color-name "gray81" "#cfcfcf")
(register-color-name "gray82" "#d1d1d1")
(register-color-name "gray83" "#d4d4d4")
(register-color-name "gray84" "#d6d6d6")
(register-color-name "gray85" "#d9d9d9")
(register-color-name "gray86" "#dbdbdb")
(register-color-name "gray87" "#dedede")
(register-color-name "gray88" "#e0e0e0")
(register-color-name "gray89" "#e3e3e3")
(register-color-name "gray90" "#e5e5e5")
(register-color-name "gray91" "#e8e8e8")
(register-color-name "gray92" "#ebebeb")
(register-color-name "gray93" "#ededed")
(register-color-name "gray94" "#f0f0f0")
(register-color-name "gray95" "#f2f2f2")
(register-color-name "gray96" "#f5f5f5")
(register-color-name "gray97" "#f7f7f7")
(register-color-name "gray98" "#fafafa")
(register-color-name "gray99" "#fcfcfc")
(register-color-name "gray100" "#ffffff")

