(cl:in-package #:cl-user)

(defpackage #:claraoke-text
  (:use #:common-lisp)
  (:intern
   #:%compare-override
   #:*batch-predicate*
   #:*change-karaoke-type*
   #:*char-inside-parenthesis-predicate*
   #:*consonants*
   #:*index*
   #:*keep-original-modifier-predicate*
   #:*length*
   #:*remove-unknown-modifier-predicate*
   #:*spell-duration-in-centiseconds*
   #:*string*
   #:*strong-consonants*
   #:*text-index*
   #:*vowels*
   #:*weak-consonants*
   #:.shadow
   #:advance
   #:alignment
   #:alignment-numpad
   #:alpha
   #:alpha1
   #:alpha2
   #:alpha3
   #:alpha4
   #:blur
   #:blur-edges
   #:border
   #:border-x
   #:border-y
   #:build-string-or-override
   #:clip-drawing
   #:clip-drawing-scaled
   #:clip-rectangle
   #:compute-override
   #:consume
   #:consume-modifier
   #:consume-override
   #:consume-spelling
   #:consume-text
   #:drawing-baseline-offset
   #:drawing-mode
   #:fad
   #:fade
   #:fontencoding
   #:fontname
   #:fontrotate
   #:fontrotate-x
   #:fontrotate-y
   #:fontrotate-z
   #:fontscale-x
   #:fontscale-y
   #:fontshear-x
   #:fontshear-y
   #:fontsize
   #:fontspace
   #:format-control
   #:iclip-drawing
   #:iclip-drawing-scaled
   #:iclip-rectangle
   #:insert-karaoke
   #:karaoke
   #:karaoke-capital
   #:karaoke-fill
   #:karaoke-outline
   #:move
   #:origin
   #:peek
   #:pos
   #:shadow-x
   #:shadow-y
   #:split-modifier
   #:symbol-from-string
   #:transformation1
   #:transformation2
   #:transformation3
   #:transformation4
   #:unknown
   #:valid-index-p
   #:wrapping-style)
  (:export
   #:batch
   #:bold
   #:color
   #:color1
   #:color2
   #:color3
   #:color4
   #:defile-text
   #:duplicate-modifier-p
   #:italic
   #:merge-overrides
   #:modifier
   #:modifier-from-string
   #:newline
   #:normalize-overrides
   #:override
   #:override-from-string
   #:override-greaterp
   #:override-lessp
   #:print-override
   #:purify-text
   #:reset
   #:same-override-p
   #:strikeout
   #:text
   #:underline))

